version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      maven-patch-group:
        update-types:
        - "patch"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "scg-docker/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
