ARG JAVA_VERSION=21

FROM eclipse-temurin:${JAVA_VERSION} AS smart-cache-graph

ARG FUSEKI_DIR=/fuseki

RUN apt-get update && \
    apt-get install -y --no-install-recommends dumb-init && \
    apt-get clean && \
    apt-get install maven -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR $FUSEKI_DIR

RUN useradd fuseki

ARG LOGS=${FUSEKI_DIR}/logs
ARG DATA=${FUSEKI_DIR}/databases
ARG CONFIGS=${FUSEKI_DIR}/config
ARG LIB=${FUSEKI_DIR}/lib
ARG AGENTS=${FUSEKI_DIR}/agents
ARG SBOMS=/opt/telicent/sbom
ARG SCG_DOCKER=${FUSEKI_DIR}/scg-docker

COPY scg-docker/entrypoint.sh .
COPY scg-docker/logback.xml .

RUN \
    mkdir -p $LOGS $DATA $CONFIGS $LIB $AGENTS $SBOMS $SCG_DOCKER && \
    chown -R fuseki ${FUSEKI_DIR} && \
    chmod a+x entrypoint.sh

ADD pom.xml ${FUSEKI_DIR}/pom.xml
ADD scg-docker/pom.xml ${SCG_DOCKER}/pom.xml
RUN mvn -pl scg-docker verify --fail-never

# Build location of the jars we need.
RUN sed '/<version>/!d;s? ??g;s?</.*??g;s?.*>??g' pom.xml  | head -1 > VERSION
RUN PROJECT_VERSION_=`cat VERSION`
#ARG PROJECT_VERSION="`cat\ VERSION`"
ENV PROJECT_VERSION=0.82.7-SNAPSHOT
ARG FUSEKI_JAR

## Collected jars
ARG JARS=scg-docker/target/dependency
COPY ${JARS} lib
ARG AGENTS=scg-docker/target/agents
COPY ${AGENTS} agents
ARG SBOM=scg-docker/target/docker-${PROJECT_VERSION}-bom.json
COPY ${SBOM} /opt/telicent/sbom/smart-cache-graph-${PROJECT_VERSION}-bom.json

ARG CONFIG=scg-docker/mnt/config
COPY ${CONFIG} config

## Default environment variables.
ENV \
    JWKS_URL="disabled"  \
    JAVA_OPTIONS="-Xmx2048m -Xms2048m"  \
    FUSEKI_JAR="${FUSEKI_JAR}"          \
    FUSEKI_DIR="${FUSEKI_DIR}"          \
    ROCKSDB_MUSL_LIBC="false"            \
    LOG_CONFIG_FILE="/fuseki/logback.xml"

USER fuseki

EXPOSE 3030

ENTRYPOINT [ "/usr/bin/dumb-init", "-v", "--single-child", "--", "./entrypoint.sh", "--config", "config/config-abac-local.ttl"]
CMD []
