ARG JAVA_VERSION=21

FROM eclipse-temurin:${JAVA_VERSION} AS smart-cache-graph

ARG FUSEKI_DIR=/fuseki

RUN apt-get update && \
    apt-get install -y --no-install-recommends dumb-init && \
    apt-get clean && \
    apt-get install maven -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR $FUSEKI_DIR

RUN useradd fuseki

ARG LOGS=${FUSEKI_DIR}/logs
ARG DATA=${FUSEKI_DIR}/databases
ARG CONFIGS=${FUSEKI_DIR}/config
ARG LIB=${FUSEKI_DIR}/lib
ARG AGENTS=${FUSEKI_DIR}/agents
ARG SBOMS=/opt/telicent/sbom
ARG SCG_DOCKER=${FUSEKI_DIR}/scg-docker
ARG SCG_SYSTEM=${FUSEKI_DIR}/scg-system
ARG SCG_SERVER=${FUSEKI_DIR}/scg-server

COPY scg-docker/entrypoint.sh .
COPY scg-docker/logback.xml .
#RUN echo "root:root" | chpasswd
RUN \
    mkdir -p $LOGS $DATA $CONFIGS $LIB $AGENTS $SBOMS $SCG_DOCKER $SCG_SYSTEM $SCG_SERVER && \
    chown -R fuseki ${FUSEKI_DIR} && \
    chmod a+x entrypoint.sh

ADD pom.xml ${FUSEKI_DIR}/pom.xml
ADD scg-docker/pom.xml ${SCG_DOCKER}/pom.xml
ADD scg-system/pom.xml ${SCG_SYSTEM}/pom.xml
ADD scg-server/pom.xml ${SCG_SERVER}/pom.xml
#RUN mvn -pl scg-docker verify --fail-never

RUN sed '/<version>/!d;s? ??g;s?</.*??g;s?.*>??g' pom.xml  | head -1 > VERSION
RUN PROJECT_VERSION_=`cat VERSION`
#ARG PROJECT_VERSION="`cat\ VERSION`"   !!!Project version still has to be h/coded here !!
ENV PROJECT_VERSION=0.82.7-SNAPSHOT
ARG FUSEKI_JAR

# Build location of the jars we need.
COPY scg-system/src scg-system/src
COPY scg-server/src scg-server/src
RUN mvn package -Dmaven.test.skip -Dmaven.javadoc.skip=false

## Collected jars
RUN mv scg-docker/target/dependency/* lib/.
RUN mv scg-docker/target/agents/* agents/.
RUN mv scg-docker/target/docker-${PROJECT_VERSION}-bom.json /opt/telicent/sbom/.

ARG CONFIG=scg-docker/mnt/config
COPY ${CONFIG} config

## Default environment variables.
ENV \
    JWKS_URL="disabled"  \
    JAVA_OPTIONS="-Xmx2048m -Xms2048m"  \
    FUSEKI_JAR="${FUSEKI_JAR}"          \
    FUSEKI_DIR="${FUSEKI_DIR}"          \
    ROCKSDB_MUSL_LIBC="false"            \
    LOG_CONFIG_FILE="/fuseki/logback.xml"

USER fuseki

EXPOSE 3030

ENTRYPOINT [ "/usr/bin/dumb-init", "-v", "--single-child", "--", "./entrypoint.sh", "--config", "config/config-abac-local.ttl"]
CMD []
