services:
  telicent-smart-cache-graph:
    networks:
      - graph
    environment:
      - FUSEKI_CONFIG=smart-cache-graph-config.ttl
      - ROUTE_TO_NAMED_GRAPHS=true
    image: telicent/smart-cache-graph:latest
    