{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.configMap.existingEnvConfigMap -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "deletion-worker.envConfigMapName" . }}
  namespace: {{ include "deletion-worker.namespace" . | quote }}
  labels:
    {{- include "deletion-worker.labels" . | nindent 4 }}

data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
  KAFKA_TOPIC: {{ .Values.deletionWorker.topic | quote }}
  KAFKA_CONFIG_FILE_PATH: /app/config/kafka-auth/kafka-config.properties
  USERINFO_URL: {{ printf "http://%s%s" (include "deletion-worker.hostAuth" . ) "/userinfo" | quote }}

  {{- if .Values.extraEnvVars }}
  {{- range .Values.extraEnvVars }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
  {{- end }}
{{- end }}