{{- /*
Copyright (C) 2026 Telicent Limited
*/}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "deletion-worker.fullname" . }}
  namespace: {{ include "deletion-worker.namespace" . | quote }}
  labels:
    {{- include "deletion-worker.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "deletion-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deletion-worker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ include "deletion-worker.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "deletion-worker.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          envFrom:
            - configMapRef:
                name: {{ include "deletion-worker.envConfigMapName" . }}
                optional: true

          ports:
            - name: http
              protocol: TCP
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
{{/*            successThreshold: {{ .Values.livenessProbe.successThreshold }}*/}}


          volumeMounts:
          {{- if .Values.global.truststore.existingSecret }}
            - name: java-truststore
              mountPath: {{ .Values.global.truststore.mountPath | default "/app/config/truststore" }}
          {{- end }}
            - name: kafka-auth-config
              mountPath: /app/config/kafka-auth/

      volumes:
        {{- if .Values.global.truststore.existingSecret }}
        - name: java-truststore
          secret:
            secretName: {{ .Values.global.truststore.existingSecret }}
        {{- end }}
        - name: kafka-auth-config
          secret:
          {{- if .Values.global.kafka.existingConfigSecretName }}
            secretName: {{ .Values.global.kafka.existingConfigSecretName }}
          {{- else }}
            secretName: {{ include "deletion-worker.fullname" . }}-kafka-config
          {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}