{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.global.kafka.existingConfigSecretName }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "deletion-worker.fullname" . }}-kafka-config
  namespace: {{ include "deletion-worker.namespace" . | quote }}
  labels:
    {{- include "deletion-worker.labels" . | nindent 4 }}
type: Opaque

data:
  kafka-config.properties: {{- (include "deletion-worker.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
{{- end }}

{{- define "deletion-worker.kafka-config-properties" -}}
  security.protocol={{ .Values.global.kafka.protocol }}
  sasl.mechanism={{ .Values.global.kafka.mechanism }}
{{- if eq .Values.global.kafka.mechanism "SCRAM-SHA-512" }}
  sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
{{- else if eq .Values.global.kafka.mechanism "PLAIN" }}
  sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
{{- end }}
  username={{ .Values.global.kafka.username | quote }} \
  password={{ .Values.global.kafka.password | quote }};
{{- end -}}