server:
  port: 8080

deletion-worker:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    config-file-path: ${KAFKA_CONFIG_FILE_PATH:}
  topic: ${KAFKA_TOPIC:RDF}
  auth:
    userinfo-url: ${USERINFO_URL:https://auth.system-integration.telicent-sandbox.telicent.live/userinfo}

management:
  endpoints:
    web:
      exposure:
        include: health