sequenceDiagram
    autonumber
    actor U as Authenticated User
    box Purple Smart Cache Graph
        participant G as GraphQL API
        participant FS as Fuseki Server
        participant J as RDF Triple Store
        participant A as ABAC Security
        participant L as Security Label Store
    end
    box Green CORE Platform
        participant UAS as User Attributes Service
    end
    U->>G: Submits Query Request
    G->>UAS: Requests User Attributes
    UAS-->>G: Returns User Attributes
    G->>FS: Submits Query
    FS->>J: Runs Query
    J->>FS: Returns Raw Results
    loop for each node
        FS->>L: Retrieves Security Label
        L-->>FS: Returns Security Label
        FS->>A: Evaluates Security
        A-->>FS: Returns Redacted Result
    end
    autonumber off
    FS-->>G: Returns Redacted Results
    G-->>U: Returns Redacted Results
    note left of G: application/graphql-response+json
