graph TD
    subgraph User
        Authenticated["Authenticated User"]
    end

    User <--> |HTTPS| Sparql
    User <--> |HTTPS| Graphql
    User --> |HTTPS| Update

    subgraph Core Platform

        subgraph Identity Services
            Identity[User Attributes Service]
        end

        subgraph Event Log
            Knowledge[Knowledge]
        end

        Knowledge -- Event Log Protocol --> Import
        Update --> CQRS
        CQRS --> Knowledge

        subgraph Smart Cache Graph
            subgraph API
                Update[SPARQL Update]
                Sparql[SPARQL Request]
                Graphql[GraphQL Request]
            end
            CQRS[CQRS Module]
            Import[Event Importer]
            Web[Fuseki Server]
            Jena[(Apache Jena)]
            Label[(Label Store)]
            ABAC[ABAC]
            Import -.-> |RDF| Jena
            Jena -.-> |Unfiltered data| ABAC
            ABAC -.-> |Redacted data| Web
            ABAC <-.-> Label
            Sparql <-.-> Web
            Graphql <-.-> Web
            Web <-- HTTPS --> Identity
            Web -.-> |Data Query| Jena
        end

    end