openapi: 3.0.3
info:
  title: Triple Access Query API
  description: API for querying access to RDF triples.
  version: 0.83.6
servers:
  - url: http://localhost:3030/
    description: Base path for query operations.
paths:
  /{datasetName}/access/query:
    post:
      summary: Return the objects for a given subject and predicate in an RDF triple
      description: Returns zero or more objects for a given subject and predicate in an RDF triple provided 1) they exist and 2) the user has access - otherwise null is returned.
      parameters:
        - name: datasetName
          in: path
          required: true
          description: The name of the dataset to query.
          schema:
            type: string
      requestBody:
        description: The subject and predicate to retrieve objects for.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                predicate:
                  type: string
            examples:
              London Population:
                value:
                  subject: http://dbpedia.org/resource/London
                  predicate: http://dbpedia.org/ontology/populationTotal
              London Country:
                value:
                  subject: http://dbpedia.org/resource/London
                  predicate: http://dbpedia.org/ontology/country
              London Birth Date:
                value:
                  subject: http://dbpedia.org/resource/London
                  predicate: http://dbpedia.org/ontology/birthDate
      responses:
        '200':
          description: Request processed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  subject:
                    type: string
                  predicate:
                    type: string
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        dataType:
                          type: string
                        value:
                          type: string
              examples:
                London Population:
                  value:
                    subject: http://dbpedia.org/resource/London
                    predicate: http://dbpedia.org/ontology/populationTotal
                    objects:
                      - dataType: http://www.w3.org/2001/XMLSchema#integer
                        value: "8799800"
                London Country:
                  value:
                    subject: http://dbpedia.org/resource/London
                    predicate: http://dbpedia.org/ontology/country
                    objects:
                      - dataType: http://www.w3.org/2001/XMLSchema#anyURI
                        value: http://dbpedia.org/resource/United_Kingdom
                      - dataType: http://www.w3.org/2001/XMLSchema#anyURI
                        value: http://dbpedia.org/resource/England
                London Birth Date:
                  value:
                    subject: http://dbpedia.org/resource/London
                    predicate: http://dbpedia.org/ontology/birthDate
                    objects: null
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
  /{datasetName}/access/triples:
    post:
      summary: Return a boolean value to indicate whether the requested triple(s) are visible to the user.
      description: Returns the request triples together with a boolean indicating whether the request triples are visible to the user, depending on 1) whether they exist 2) whether the user has access to see them 3) whether the user has indicated they want to know if all are visible or any of them.
      parameters:
        - name: datasetName
          in: path
          required: true
          description: The name of the dataset to query.
          schema:
            type: string
        - name: all
          in: query
          required: false
          description: All triples need to be visible, not just some.
          schema:
            type: boolean
            default: true
      requestBody:
        description: An array or triples, each containing the subject, predicate and object to be checked.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                triples:
                  type: array
                  items:
                    type: object
                    properties:
                      subject:
                        type: string
                      predicate:
                        type: string
                      object:
                        type: object
                        properties:
                          dataType:
                            type: string
                            description: Can be a full URI or prefixed value (eg. xsd:string)
                          value:
                            type: string
            examples:
              London:
                value:
                  triples:
                    - subject: http://dbpedia.org/resource/London
                      predicate: http://dbpedia.org/ontology/populationTotal
                      object:
                        - dataType: xsd:integer
                          value: "8799800"
                    - subject: http://dbpedia.org/resource/London
                      predicate: http://dbpedia.org/ontology/country
                      object:
                        - dataType: xsd:anyURI
                          value:  http://dbpedia.org/resource/United_Kingdom
      responses:
        '200':
          description: Request processed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  triples:
                    type: array
                    items:
                      type: object
                      properties:
                        subject:
                          type: array
                        predicate:
                          type: string
                        object:
                          type: object
                          properties:
                            dataType:
                              type: string
                            value:
                              type: string
                  visible:
                    type: boolean
              examples:
                London:
                  value:
                    triples:
                      - subject: http://dbpedia.org/resource/London
                        predicate: http://dbpedia.org/ontology/populationTotal
                        object:
                          - dataType: xsd:integer
                            value: "8799800"
                      - subject: http://dbpedia.org/resource/London
                        predicate: http://dbpedia.org/ontology/country
                        object:
                          - dataType: xsd:anyURI
                            value: http://dbpedia.org/resource/United_Kingdom
                    visible: true
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.