{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.global.kafka.existingConfigSecretName }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "graph.fullname" . }}-kafka-config
  namespace: {{ include "graph.namespace" . | quote }}
  labels:
    {{- include "graph.labels" . | nindent 4 }}
type: Opaque

data:
  kafka-config.properties: {{- (include "graph.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
  kafka-config.toml: {{- (include "graph.kafka-config-toml" . ) | b64enc | indent 1 }}
  application.properties: {{- (include "graph.application-properties" . ) | b64enc | toYaml | indent 1 }}
{{- end }}

{{/*
Copyright (C) 2026 Telicent Limited
*/}}
{{- define "graph.kafka-config-properties" -}}
      security.protocol={{ .Values.global.kafka.protocol }}
      sasl.mechanism={{ .Values.global.kafka.mechanism }}
      {{- if eq .Values.global.kafka.mechanism "SCRAM-SHA-512" }}
      sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      {{- else if eq .Values.global.kafka.mechanism "PLAIN" }}
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      {{- end }}
        username={{ .Values.global.kafka.username | quote }} \
        password={{ .Values.global.kafka.password | quote }};
{{- end  -}}

{{- define "graph.kafka-config-toml" -}}
bootstrap.servers={{ .Values.global.kafka.bootstrapServers }}
security.protocol={{ .Values.global.kafka.protocol }}
sasl.mechanism={{ .Values.global.kafka.mechanism }}
sasl.username={{ .Values.global.kafka.username | replace "\"" "" }}
sasl.password={{ .Values.global.kafka.password | replace "\"" "" }}
{{- end  -}}

{{- define "graph.application-properties" -}}
      camel.component.kafka.security-protocol={{ .Values.global.kafka.protocol }}
      camel.component.kafka.sasl-mechanism={{ .Values.global.kafka.mechanism }}
      {{- if eq .Values.global.kafka.mechanism "SCRAM-SHA-512" }}
      camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      {{- else if eq .Values.global.kafka.mechanism "PLAIN" }}
      camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      {{- end }}
        username={{ .Values.global.kafka.username | quote }} \
        password={{ .Values.global.kafka.password | quote }};
{{- end  -}}
