name: SC Graph Build

on:
  # Run workflow for any push to a branch or a tag
  push:
    branches:
      - "**"
    tags:
      - "**"
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Only permit one build per branch/tag, except on release branches where we want all
# builds to proceed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}

jobs:
  maven-build:
    uses: telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
      pull-requests: write
    with:
      # Some Docker based tests in this repository use public images
      USES_DOCKERHUB_IMAGES: true
      # Want SNAPSHOTs to be published from main
      PUBLISH_SNAPSHOTS: true
      MAIN_BRANCH: main
      # If running in debug mode, use appropriate logging
      MAVEN_DEBUG_ARGS: -Dlogback.configurationFile=logback-debug.xml
      RUN_WINDOWS_BUILD: false
      JAVA_VERSION: 21
      PUBLISH_JACOCO_REPORT: true
    secrets: inherit

  docker-build:
    name: Build and push to ECR (${{ matrix.image }})
    strategy:
      matrix:
        image: [smart-cache-graph]
        chartName: [graph]
      fail-fast: false
    needs: maven-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Build and push image to ECR
        uses: telicent-oss/shared-workflows/.github/actions/push-container-image@main
        with:
          app-name: ${{ matrix.image }}
          app-name-prefix: ""
          dockerfile: scg-docker/Dockerfile
          version: ${{ needs.maven-build.outputs.version }}
          target: ${{ matrix.image }}
          java-version: 21
          uses-maven: true
          registry: aws
          fail-on-unfixed: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          download-sbom: "false"
          enable-buildkit-cache: "true"
          build-args: |
            PROJECT_VERSION=${{ needs.maven-build.outputs.version }}

      - name: Package and push Helm charts to ECR
        uses: telicent-oss/shared-workflows/.github/actions/push-helm-chart@main
        with:
          app-name: ${{ matrix.chartName }}
          app-name-prefix: ""
          chart: charts/${{ matrix.chartName}}
          registry: aws
          version: ${{ needs.maven-build.outputs.version }}
          appVersion: ${{ needs.maven-build.outputs.version }}
          replace-chart-versions: true
