name: SC Graph Build

on:
  # Run workflow for any push to a branch or a tag
  push:
    branches:
      - '**'
    tags:
      - '**'
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Only permit one build per branch/tag, except on release branches where we want all
# builds to proceed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}
    
jobs:
  maven-build:
    uses: telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    with:
      # Some Docker based tests in this repository use public images
      USES_DOCKERHUB_IMAGES: true
      # Want SNAPSHOTs to be published from main
      PUBLISH_SNAPSHOTS: true
      MAIN_BRANCH: main
      # If running in debug mode, use appropriate logging
      MAVEN_DEBUG_ARGS: -Dlogback.configurationFile=logback-debug.xml
      RUN_WINDOWS_BUILD: false
      JAVA_VERSION: 21
      PUBLISH_JACOCO_REPORT: true
    secrets: inherit

  docker-build:
    strategy:
      matrix:
        image: [ smart-cache-graph ]
      fail-fast: false
    needs: maven-build
    uses: telicent-oss/shared-workflows/.github/workflows/docker-push-to-registries.yml@main
    with:
      APP_NAME: ${{ matrix.image }}
      APP_NAME_PREFIX: ""
      PATH: .
      DOCKERFILE: scg-docker/Dockerfile
      VERSION: ${{ needs.maven-build.outputs.version }}
      TARGET: ${{ matrix.image }}
      JAVA_VERSION: 21
      USES_MAVEN: true
      DOWNLOAD_SBOM: false
      GRYPE_SECURITY_ISSUES_BLOCK_ONLY_IF_FIX_AVAILABLE: true
      BUILD_ARGS: |
        PROJECT_VERSION=${{ needs.maven-build.outputs.version }}
    secrets: inherit
