name: Deletion Worker Build

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
    paths:
      - "scg-deletion-worker/**"
      - "charts/deletion-worker/**"
      - "pom.xml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}

jobs:
  maven-build:
    uses: telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
      pull-requests: write
    with:
      USES_DOCKERHUB_IMAGES: true
      PUBLISH_SNAPSHOTS: true
      MAIN_BRANCH: main
      MAVEN_DEBUG_ARGS: -Dlogback.configurationFile=logback-debug.xml
      RUN_WINDOWS_BUILD: false
      JAVA_VERSION: 21
      PUBLISH_JACOCO_REPORT: true
    secrets: inherit

  docker-build:
    name: Build and push to ECR (${{ matrix.image }})
    strategy:
      matrix:
        image: [scg-deletion-worker]
        chartName: [deletion-worker]
      fail-fast: false
    needs: maven-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Build and push image to ECR
        uses: telicent-oss/shared-workflows/.github/actions/push-container-image@main
        with:
          app-name: ${{ matrix.image }}
          app-name-prefix: ""
          dockerfile: scg-deletion-worker/Dockerfile
          version: ${{ needs.maven-build.outputs.version }}
          target: ${{ matrix.image }}
          java-version: 21
          uses-maven: true
          registry: aws
          fail-on-unfixed: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          download-sbom: "false"
          enable-buildkit-cache: "true"
          build-args: |
            PROJECT_VERSION=${{ needs.maven-build.outputs.version }}
#          TODO
#          remove once tested
          trivy-ignores: .trivyignore

      - name: Package and push Helm chart to ECR
        uses: telicent-oss/shared-workflows/.github/actions/push-helm-chart@main
        with:
          app-name: ${{ matrix.chartName }}
          app-name-prefix: ""
          chart: charts/${{ matrix.chartName }}
          registry: aws
          version: ${{ needs.maven-build.outputs.version }}
          appVersion: ${{ needs.maven-build.outputs.version }}
          replace-chart-versions: true